import "./globals.css";
import NavBar from "./navigation";

export const metadata = {
  title: "Portfolio By Sheila",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
